---
# Source: lab-monitoring-chart/charts/influxdb/templates/influxdb/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-influxdb
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-2.2.2
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook-weight: "9"
type: Opaque
data:
  admin-user-password: "anVuaXBlckAxMjM="
  admin-user-token: "c0RRVXpnMnl6Tm1pUk5YcHBJcjA="
  user-password: "anVuaXBlckAxMjM="
---
# Source: lab-monitoring-chart/charts/preparation/templates/secret.yaml
apiVersion: v1
data:
  GH_TOKEN: "Z2hwX25lV2JnYzl5ck1LcjlCdVd2a2NraWRUaXFwTG9wUjJwdDJRdQ=="
kind: Secret
metadata:
  name: "gh-token"
type: Opaque
---
# Source: lab-monitoring-chart/charts/syncthing/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name:  monitoring-syncthing
type: Opaque
data:
  ui-password: "anVuaXBlckAxMjM="
---
# Source: lab-monitoring-chart/charts/influxdb/templates/influxdb/configmap-cq-retention-policy.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cq-and-retention-policy
data:
  init_rp_and_cq.sh: |    
    #!/bin/bash

    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE RETENTION POLICY six_months ON influxdb_nms DURATION 26w REPLICATION 1 DEFAULT;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE RETENTION POLICY one_year ON influxdb_nms DURATION 52w REPLICATION 1;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE RETENTION POLICY infinite_time ON influxdb_nms DURATION inf REPLICATION 1;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE RETENTION POLICY forever ON influxdb_nms DURATION inf REPLICATION 1;'

    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'INSERT INTO influxdb_nms.forever rp_config,idx=1 rp="six_months",start=0i,end=15724800000i -9223372036854775806'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'INSERT INTO influxdb_nms.forever rp_config,idx=2 rp="one_year",start=15724800000i,end=31449600000i -9223372036854775806'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'INSERT INTO influxdb_nms.forever rp_config,idx=3 rp="inf_time",start=31449600000i,end=9223372036854775806i'

    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_interface-check-command" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."interface-check-command" FROM  influxdb_nms.six_months."interface-check-command" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_interface-check-command" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."interface-check-command" FROM  influxdb_nms.six_months."interface-check-command" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_check-snmp-with-oid-text-index" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."check-snmp-with-oid-text-index" FROM  influxdb_nms.six_months."check-snmp-with-oid-text-index" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_check-snmp-with-oid-text-index" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."check-snmp-with-oid-text-index" FROM  influxdb_nms.six_months."check-snmp-with-oid-text-index" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_ping4" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."ping4" FROM  influxdb_nms.six_months."ping4" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_ping4" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."ping4" FROM  influxdb_nms.six_months."ping4" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_hostalive" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."hostalive" FROM  influxdb_nms.six_months."hostalive" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_hostalive" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."hostalive" FROM  influxdb_nms.six_months."hostalive" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_load" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."load" FROM  influxdb_nms.six_months."load" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_load" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."load" FROM  influxdb_nms.six_months."load" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_disk" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."disk" FROM  influxdb_nms.six_months."disk" GROUP BY time(30m), * END;'

    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_disk" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."disk" FROM  influxdb_nms.six_months."disk" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_icinga" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."icinga" FROM  influxdb_nms.six_months."icinga" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_icinga" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."icinga" FROM  influxdb_nms.six_months."icinga" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_snmp" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."snmp" FROM  influxdb_nms.six_months."snmp" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_snmp" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."snmp" FROM  influxdb_nms.six_months."snmp" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_ssh" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."ssh" FROM  influxdb_nms.six_months."ssh" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_ssh" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."ssh" FROM  influxdb_nms.six_months."ssh" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_users" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."users" FROM  influxdb_nms.six_months."users" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_users" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."users" FROM  influxdb_nms.six_months."users" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_mem" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."mem" FROM  influxdb_nms.six_months."mem" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_mem" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."mem" FROM  influxdb_nms.six_months."mem" GROUP BY time(1h), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_12M_mailq" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.one_year."mailq" FROM  influxdb_nms.six_months."mailq" GROUP BY time(30m), * END;'
    influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_USER_PASSWORD -database $INFLUXDB_DB -execute 'CREATE CONTINUOUS QUERY "cq_6M_to_inf_mailq" ON  influxdb_nms BEGIN SELECT max(value) AS value, min(value), mean(value) INTO  influxdb_nms.infinite_time."mailq" FROM  influxdb_nms.six_months."mailq" GROUP BY time(1h), * END;'
---
# Source: lab-monitoring-chart/charts/influxdb/templates/influxdb/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: influxdb-headless
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-2.2.2
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: influxdb
  annotations:
    helm.sh/hook-weight: "9"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8086
      targetPort: http
      protocol: TCP
      name: http
    - port: 8088
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/component: influxdb
---
# Source: lab-monitoring-chart/charts/influxdb/templates/influxdb/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-2.2.2
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: influxdb
  annotations:
    helm.sh/hook-weight: "9"
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: http
      protocol: TCP
      name: http
      nodePort: null
    - port: 8088
      targetPort: rpc
      protocol: TCP
      name: rpc
      nodePort: null
  selector:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/component: influxdb