---
# Source: lab-monitoring-chart/charts/kafka/templates/kafka-persistent-single.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 3.5.1
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: nodeport
        tls: false
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.5"
      log.retention.hours: 24
    storage:
      type: persistent-claim
      #class: kafka-default
      class: local-path
      size: 20Gi
      deleteClaim: false
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 50Mi
    template:
      pod:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: kafka
                topologyKey: kubernetes.io/hostname
              weight: 1
        securityContext:
          runAsUser: 0
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      #class: zookeeper-default
      class: local-path
      size: 5Gi
      deleteClaim: false
    template:
      pod:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: zookeeper
                topologyKey: kubernetes.io/hostname
              weight: 1
        securityContext:
          runAsUser: 0
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 50Mi
  entityOperator:
    topicOperator: {}
    userOperator: {}